#include "MediaBank.h"

MediaBank MEDIA_BANK;

/***********************************************/
void initMediaBank()
/***********************************************/
{

	//Images:
	MEDIA_BANK.addImage(GRASS_IMAGE_PATH, GRASS_IMAGE, true);
	MEDIA_BANK.addImage(GRASS_IMAGE_b_PATH, GRASS_IMAGE_b, true);
	MEDIA_BANK.addImage(GRASS_IMAGE_c_PATH, GRASS_IMAGE_c, true);
	MEDIA_BANK.addImage(GRASS_INACTIVE_IMAGE_c_PATH, GRASS_INACTIVE_IMAGE_c, true);
	MEDIA_BANK.addImage(ROAD_BLOCK_IMAGE_PATH, ROAD_BLOCK_IMAGE);
	MEDIA_BANK.addImage(ROAD_BLOCK_INACTIVE_IMAGE_PATH, ROAD_BLOCK_INACTIVE_IMAGE);

	MEDIA_BANK.addImage(START_BLOCK_IMAGE_PATH, START_BLOCK_IMAGE);
	MEDIA_BANK.addImage(END_BLOCK_IMAGE_PATH, END_BLOCK_IMAGE);

	MEDIA_BANK.addImage(EAST_WEST_IMAGE_PATH, EAST_WEST_IMAGE, true);
	MEDIA_BANK.addImage(SOUTH_NORTH_IMAGE_PATH, SOUTH_NORTH_IMAGE, true);

	MEDIA_BANK.addImage(NORTH_EAST_IMAGE_PATH, NORTH_EAST_IMAGE, true);
	MEDIA_BANK.addImage(NORTH_WEST_IMAGE_PATH, NORTH_WEST_IMAGE, true);

	MEDIA_BANK.addImage(SOUTH_EAST_IMAGE_PATH, SOUTH_EAST_IMAGE, true);
	MEDIA_BANK.addImage(SOUTH_WEST_IMAGE_PATH, SOUTH_WEST_IMAGE, true);

	

	MEDIA_BANK.addImage(STONE_BULLET_IMAGE_PATH, STONE_BULLET_IMAGE);

	MEDIA_BANK.addImage(TOWER_WOOD_IMAGE_PATH, TOWER_WOOD_IMAGE);
	MEDIA_BANK.addImage(TOWER_BOX_01_IMAGE_PATH, TOWER_BOX_01_IMAGE);
	

	MEDIA_BANK.addImage(MENU_IMAGE_PATH, MENU_IMAGE);
	MEDIA_BANK.addImage(PAUSE_IMAGE_PATH, PAUSE_IMAGE);

	MEDIA_BANK.addImage(BUMPER_IMAGE_PATH, BUMPER_IMAGE);

	MEDIA_BANK.addImage(MOBT1_IMAGE_PATH, MOBT1_IMAGE);

	MEDIA_BANK.addImage(TOWER1_BUTTON_IMAGE_PATH, TOWER1_BUTTON_IMAGE);
	MEDIA_BANK.addImage(TOWER1_BUTTON_IMAGE_P_PATH, TOWER1_BUTTON_IMAGE_P);

	MEDIA_BANK.addImage(CELL_SELECT_MARK_PATH, CELL_SELECT_MARK, true);

	MEDIA_BANK.addImage(BUY_TOWER_BUTTON_IMAGE_PATH, BUY_TOWER_BUTTON_IMAGE);
	MEDIA_BANK.addImage(BUY_BUILDING_BUTTON_IMAGE_PATH, BUY_BUILDING_BUTTON_IMAGE);
	MEDIA_BANK.addImage(BUY_OTHER_BUTTON_IMAGE_PATH, BUY_OTHER_BUTTON_IMAGE);
	MEDIA_BANK.addImage(SET_BUILDING_DIR_BUTTON_IMAGE_PATH, SET_BUILDING_DIR_BUTTON_IMAGE);
	MEDIA_BANK.addImage(UPGRADE_TOWER_BUTTON_IMAGE_PATH, UPGRADE_TOWER_BUTTON_IMAGE);

	MEDIA_BANK.addImage(BUY_TOWER_BUTTON_P_IMAGE_PATH, BUY_TOWER_BUTTON_P_IMAGE);
	MEDIA_BANK.addImage(BUY_BUILDING_BUTTON_P_IMAGE_PATH, BUY_BUILDING_BUTTON_P_IMAGE);
	MEDIA_BANK.addImage(BUY_OTHER_BUTTON_P_IMAGE_PATH, BUY_OTHER_BUTTON_P_IMAGE);
	MEDIA_BANK.addImage(SET_BUILDING_DIR_BUTTON_P_IMAGE_PATH, SET_BUILDING_DIR_BUTTON_P_IMAGE);
	MEDIA_BANK.addImage(UPGRADE_TOWER_BUTTON_P_IMAGE_PATH, UPGRADE_TOWER_BUTTON_P_IMAGE);

	MEDIA_BANK.addImage(BUY_TOWER_BUTTON_I_IMAGE_PATH, BUY_TOWER_BUTTON_I_IMAGE);
	MEDIA_BANK.addImage(BUY_BUILDING_BUTTON_I_IMAGE_PATH, BUY_BUILDING_BUTTON_I_IMAGE);
	MEDIA_BANK.addImage(BUY_OTHER_BUTTON_I_IMAGE_PATH, BUY_OTHER_BUTTON_I_IMAGE);
	MEDIA_BANK.addImage(SET_BUILDING_DIR_BUTTON_I_IMAGE_PATH, SET_BUILDING_DIR_BUTTON_I_IMAGE);
	MEDIA_BANK.addImage(UPGRADE_TOWER_BUTTON_I_IMAGE_PATH, UPGRADE_TOWER_BUTTON_I_IMAGE);

	MEDIA_BANK.addImage(ARROW_DIRECTION_IMAGE_PATH, ARROW_DIRECTION_IMAGE);
	
	MEDIA_BANK.addImage(TOWER_RANGE_INDICATOR_IMAGE_PATH, TOWER_RANGE_INDICATOR_IMAGE);

	MEDIA_BANK.addImage(TOWER_DIRECTION_BUTTON_IMAGE_PATH, TOWER_DIRECTION_BUTTON_IMAGE);
	MEDIA_BANK.addImage(TOWER_DIRECTION_BUTTON_P_IMAGE, TOWER_DIRECTION_BUTTON_P_IMAGE);
	MEDIA_BANK.addImage(TOWER_DIRECTION_BUTTON_I_IMAGE_PATH, TOWER_DIRECTION_BUTTON_I_IMAGE);

	MEDIA_BANK.addImage(COIN_IMAGE_PATH, COIN_IMAGE);



	//Fonts:
	MEDIA_BANK.addFont(FONT1_PATH, FONT1);

	//Sounds:
	MEDIA_BANK.addSound(BG_MUSIC_01_PATH, BG_MUSIC_01, true);
	MEDIA_BANK.addSound(BG_MUSIC_02_PATH, BG_MUSIC_02, false);
	MEDIA_BANK.addSound(SHOOT_TICK_PATH, SHOOT_TICK, false);

}